version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=defaultdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data